# Generated by Django 4.0.5 on 2022-06-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='post/image'),
        ),
    ]
