# Generated by Django 4.0.5 on 2022-08-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_cover_image_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(default='default.jpg', upload_to='avatars'),
        ),
    ]
